---
version: "3"

includes:
  scripts: .tasks/scripts.yml
  _node: .tasks/node.yml

tasks:
  default:
    desc: Default command, list tasks
    cmds:
      - task -l

  docker:build:prod:
    desc: Build Production Docker image
    cmds:
      - task: scripts:build:docker:prod

  npm:upgrade:
    desc: Upgrade ALL packages to latest versions (no prompts)
    dir: svelte-page
    cmds:
      - task: _node:npm:upgrade

  npm:update:
    desc: Safe semver update of packages.json
    dir: svelte-page
    cmds:
      - task: _node:npm:update

  serve:dev:
    desc: Start dev server
    dir: svelte-page
    cmds:
      - task: _node:npm:serve:dev
