---
version: "3"

includes:
  scripts: .tasks/scripts.yml
  _node: .tasks/node.yml
  docker: .tasks/docker.yml

vars:
  CONTAINER_NAME: base-layer-site
  HOST_PORT: 80
  IMAGE_NAME: base-layer
  DOCKERFILE: .containers/prod/Dockerfile
  CONTEXT_PATH: ./svelte-page

tasks:
  default:
    desc: Default command, list tasks
    cmds:
      - task -l

  docker:build:prod:
    desc: Build Production Docker image
    cmds:
      - task: docker:build

  docker:run:prod:
    desc: Start Production container. Override vars by passing them at the end, i.e. task docker:run:prod HOST_PORT=3000
    cmds:
      - task: docker:run

  npm:upgrade:
    desc: Upgrade ALL packages to latest versions (no prompts)
    dir: svelte-page
    cmds:
      - task: _node:npm:upgrade

  npm:update:
    desc: Safe semver update of packages.json
    dir: svelte-page
    cmds:
      - task: _node:npm:update

  serve:dev:
    desc: Start dev server
    dir: svelte-page
    cmds:
      - task: _node:npm:serve:dev
